export interface MenuItem {
  id: number
  name: string
  price: number
  category: string
  image: string
  description: string
  isVeg: boolean
  spiceLevel?: number
  preparationTime?: number
  isPopular?: boolean
  allergens?: string[]
}

export const menuItems: MenuItem[] = [
  // Main Course - Non-Veg
  {
    id: 1,
    name: "Butter Chicken",
    price: 320,
    category: "Main Course",
    image: "/chicken-biryani-rice.jpg",
    description: "Creamy tomato-based curry with tender chicken pieces",
    isVeg: false,
    spiceLevel: 2,
    preparationTime: 25,
    isPopular: true,
    allergens: ["dairy", "nuts"],
  },
  {
    id: 2,
    name: "Chicken Tikka Masala",
    price: 340,
    category: "Main Course",
    image: "/chicken-biryani-rice.jpg",
    description: "Grilled chicken in rich tomato and cream sauce",
    isVeg: false,
    spiceLevel: 3,
    preparationTime: 30,
    isPopular: true,
    allergens: ["dairy"],
  },
  {
    id: 3,
    name: "Lamb Rogan Josh",
    price: 420,
    category: "Main Course",
    image: "/chicken-biryani-rice.jpg",
    description: "Tender lamb cooked in aromatic Kashmiri spices",
    isVeg: false,
    spiceLevel: 3,
    preparationTime: 45,
    allergens: ["dairy"],
  },
  {
    id: 4,
    name: "Fish Curry",
    price: 380,
    category: "Main Course",
    image: "/chicken-biryani-rice.jpg",
    description: "Fresh fish in coconut and curry leaf gravy",
    isVeg: false,
    spiceLevel: 2,
    preparationTime: 20,
    allergens: ["fish"],
  },
  {
    id: 5,
    name: "Chicken Korma",
    price: 310,
    category: "Main Course",
    image: "/chicken-biryani-rice.jpg",
    description: "Mild chicken curry with cashew and yogurt base",
    isVeg: false,
    spiceLevel: 1,
    preparationTime: 25,
    allergens: ["dairy", "nuts"],
  },

  // Main Course - Veg
  {
    id: 6,
    name: "Paneer Tikka Masala",
    price: 280,
    category: "Main Course",
    image: "/paneer-tikka-grilled.jpg",
    description: "Grilled paneer in rich tomato gravy",
    isVeg: true,
    spiceLevel: 2,
    preparationTime: 20,
    isPopular: true,
    allergens: ["dairy"],
  },
  {
    id: 7,
    name: "Palak Paneer",
    price: 260,
    category: "Main Course",
    image: "/paneer-tikka-grilled.jpg",
    description: "Cottage cheese in creamy spinach gravy",
    isVeg: true,
    spiceLevel: 1,
    preparationTime: 18,
    allergens: ["dairy"],
  },
  {
    id: 8,
    name: "Malai Kofta",
    price: 290,
    category: "Main Course",
    image: "/paneer-tikka-grilled.jpg",
    description: "Fried cottage cheese balls in creamy gravy",
    isVeg: true,
    spiceLevel: 1,
    preparationTime: 25,
    allergens: ["dairy", "nuts"],
  },
  {
    id: 9,
    name: "Baingan Bharta",
    price: 240,
    category: "Main Course",
    image: "/paneer-tikka-grilled.jpg",
    description: "Roasted eggplant mash with spices",
    isVeg: true,
    spiceLevel: 2,
    preparationTime: 20,
  },

  // Rice & Biryani
  {
    id: 10,
    name: "Chicken Biryani",
    price: 350,
    category: "Rice & Biryani",
    image: "/chicken-biryani-rice.jpg",
    description: "Aromatic basmati rice with spiced chicken",
    isVeg: false,
    spiceLevel: 3,
    preparationTime: 35,
    isPopular: true,
    allergens: ["dairy"],
  },
  {
    id: 11,
    name: "Mutton Biryani",
    price: 420,
    category: "Rice & Biryani",
    image: "/chicken-biryani-rice.jpg",
    description: "Fragrant rice with tender mutton pieces",
    isVeg: false,
    spiceLevel: 3,
    preparationTime: 45,
    allergens: ["dairy"],
  },
  {
    id: 12,
    name: "Vegetable Biryani",
    price: 280,
    category: "Rice & Biryani",
    image: "/chicken-biryani-rice.jpg",
    description: "Mixed vegetables with aromatic basmati rice",
    isVeg: true,
    spiceLevel: 2,
    preparationTime: 25,
    allergens: ["dairy", "nuts"],
  },
  {
    id: 13,
    name: "Jeera Rice",
    price: 180,
    category: "Rice & Biryani",
    image: "/chicken-biryani-rice.jpg",
    description: "Cumin flavored basmati rice",
    isVeg: true,
    spiceLevel: 0,
    preparationTime: 15,
  },
  {
    id: 14,
    name: "Pulao Rice",
    price: 200,
    category: "Rice & Biryani",
    image: "/chicken-biryani-rice.jpg",
    description: "Fragrant rice with whole spices",
    isVeg: true,
    spiceLevel: 1,
    preparationTime: 20,
  },

  // Dal & Curry
  {
    id: 15,
    name: "Dal Makhani",
    price: 220,
    category: "Dal & Curry",
    image: "/dal-makhani-curry.jpg",
    description: "Creamy black lentils slow-cooked with butter",
    isVeg: true,
    spiceLevel: 1,
    preparationTime: 30,
    isPopular: true,
    allergens: ["dairy"],
  },
  {
    id: 16,
    name: "Dal Tadka",
    price: 180,
    category: "Dal & Curry",
    image: "/dal-makhani-curry.jpg",
    description: "Yellow lentils tempered with spices",
    isVeg: true,
    spiceLevel: 2,
    preparationTime: 20,
  },
  {
    id: 17,
    name: "Chana Masala",
    price: 200,
    category: "Dal & Curry",
    image: "/dal-makhani-curry.jpg",
    description: "Spiced chickpeas in tomato gravy",
    isVeg: true,
    spiceLevel: 2,
    preparationTime: 25,
  },
  {
    id: 18,
    name: "Rajma Curry",
    price: 210,
    category: "Dal & Curry",
    image: "/dal-makhani-curry.jpg",
    description: "Red kidney beans in spiced gravy",
    isVeg: true,
    spiceLevel: 2,
    preparationTime: 30,
  },

  // Breads
  {
    id: 19,
    name: "Butter Naan",
    price: 60,
    category: "Breads",
    image: "/butter-naan.png",
    description: "Soft leavened bread with butter",
    isVeg: true,
    preparationTime: 8,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 20,
    name: "Garlic Naan",
    price: 70,
    category: "Breads",
    image: "/butter-naan.png",
    description: "Naan bread topped with garlic and herbs",
    isVeg: true,
    preparationTime: 10,
    isPopular: true,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 21,
    name: "Cheese Naan",
    price: 90,
    category: "Breads",
    image: "/butter-naan.png",
    description: "Naan stuffed with melted cheese",
    isVeg: true,
    preparationTime: 12,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 22,
    name: "Tandoori Roti",
    price: 40,
    category: "Breads",
    image: "/butter-naan.png",
    description: "Whole wheat bread from tandoor",
    isVeg: true,
    preparationTime: 6,
    allergens: ["gluten"],
  },
  {
    id: 23,
    name: "Laccha Paratha",
    price: 55,
    category: "Breads",
    image: "/butter-naan.png",
    description: "Layered flatbread with ghee",
    isVeg: true,
    preparationTime: 10,
    allergens: ["gluten", "dairy"],
  },

  // Beverages
  {
    id: 24,
    name: "Mango Lassi",
    price: 120,
    category: "Beverages",
    image: "/mango-lassi.png",
    description: "Refreshing yogurt drink with mango",
    isVeg: true,
    preparationTime: 5,
    isPopular: true,
    allergens: ["dairy"],
  },
  {
    id: 25,
    name: "Sweet Lassi",
    price: 100,
    category: "Beverages",
    image: "/mango-lassi.png",
    description: "Traditional sweet yogurt drink",
    isVeg: true,
    preparationTime: 5,
    allergens: ["dairy"],
  },
  {
    id: 26,
    name: "Masala Chai",
    price: 60,
    category: "Beverages",
    image: "/mango-lassi.png",
    description: "Spiced tea with milk and herbs",
    isVeg: true,
    preparationTime: 8,
    allergens: ["dairy"],
  },
  {
    id: 27,
    name: "Fresh Lime Soda",
    price: 80,
    category: "Beverages",
    image: "/mango-lassi.png",
    description: "Refreshing lime with soda water",
    isVeg: true,
    preparationTime: 3,
  },
  {
    id: 28,
    name: "Buttermilk",
    price: 70,
    category: "Beverages",
    image: "/mango-lassi.png",
    description: "Spiced yogurt drink with mint",
    isVeg: true,
    preparationTime: 5,
    allergens: ["dairy"],
  },

  // Desserts
  {
    id: 29,
    name: "Gulab Jamun",
    price: 140,
    category: "Desserts",
    image: "/gulab-jamun-dessert.png",
    description: "Sweet milk dumplings in sugar syrup",
    isVeg: true,
    preparationTime: 5,
    isPopular: true,
    allergens: ["dairy", "gluten"],
  },
  {
    id: 30,
    name: "Ras Malai",
    price: 160,
    category: "Desserts",
    image: "/gulab-jamun-dessert.png",
    description: "Soft cheese patties in sweet milk",
    isVeg: true,
    preparationTime: 5,
    allergens: ["dairy"],
  },
  {
    id: 31,
    name: "Kulfi",
    price: 120,
    category: "Desserts",
    image: "/gulab-jamun-dessert.png",
    description: "Traditional Indian ice cream",
    isVeg: true,
    preparationTime: 2,
    allergens: ["dairy", "nuts"],
  },
  {
    id: 32,
    name: "Kheer",
    price: 130,
    category: "Desserts",
    image: "/gulab-jamun-dessert.png",
    description: "Rice pudding with cardamom and nuts",
    isVeg: true,
    preparationTime: 5,
    allergens: ["dairy", "nuts"],
  },

  // Starters
  {
    id: 33,
    name: "Chicken Tikka",
    price: 280,
    category: "Starters",
    image: "/paneer-tikka-grilled.jpg",
    description: "Grilled chicken marinated in yogurt and spices",
    isVeg: false,
    spiceLevel: 2,
    preparationTime: 20,
    isPopular: true,
    allergens: ["dairy"],
  },
  {
    id: 34,
    name: "Paneer Tikka",
    price: 240,
    category: "Starters",
    image: "/paneer-tikka-grilled.jpg",
    description: "Grilled cottage cheese with bell peppers",
    isVeg: true,
    spiceLevel: 2,
    preparationTime: 15,
    allergens: ["dairy"],
  },
  {
    id: 35,
    name: "Samosa",
    price: 80,
    category: "Starters",
    image: "/paneer-tikka-grilled.jpg",
    description: "Crispy pastry with spiced potato filling",
    isVeg: true,
    spiceLevel: 1,
    preparationTime: 10,
    allergens: ["gluten"],
  },
]

export const categories = [
  "All",
  "Main Course",
  "Rice & Biryani",
  "Dal & Curry",
  "Breads",
  "Beverages",
  "Desserts",
  "Starters",
]
